name: Build and Deploy

on:
  push:
    branches:
      - gh-actions

jobs:
  # build:
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Build and Push Docker image
  #       run: |
  #         docker build -t ttl.sh/hesamzkr-python-app .
  #         docker push ttl.sh/hesamzkr-python-app

  deploy:
    runs-on: self-hosted
    # needs: build

    steps:
      - name: Deploy to target VM
        env:
          DEPLOY_HOST: 192.168.105.3
          DEPLOY_USER: vagrant
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "${SSH_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key ${DEPLOY_USER}@${DEPLOY_HOST} << 'EOF'
            docker stop my-python-app || true
            docker rm my-python-app || true
            docker run -d -p 80:4444 --name hesamzkr-python-app ttl.sh/hesamzkr-python-app:latest
